name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - go.*
      - main.go
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

env:
  BINARY_NAME: summon-secrets-manager
  BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
  CC: musl-gcc
  # CC: x86_64-unknown-linux-musl-cc
  CGO_ENABLED: 1

  # https://github.com/bitwarden/sdk-go/blob/main/INSTRUCTIONS.md#build
  LDFLAGS: '-linkmode external -extldflags "-static -Wl,-unresolved-symbols=ignore-all" -s -w'

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install musl
      run: |
        sudo apt update
        sudo apt -y install musl-tools

        # Install cross-compilation toolchain with musl libc
        declare -A binary

        binary['aarch64-unknown-linux-musl']="20250911"
        # binary['x86_64-unknown-linux-musl']="20250911"
        binary['x86_64-w64-mingw32']="20250206"

        mkdir -p $XTOOLS
        for name in "${!binary[@]}"; do
          version=$"${binary[$name]}"
          wget -nv -O - https://github.com/musl-cross/musl-cross/releases/download/${version}/${name}.tar.xz | tar -Jxf - -C $XTOOLS
          echo "${XTOOLS}/${name}/bin" >>$GITHUB_PATH
        done
      env:
        XTOOLS: /opt/x-tools

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Test
      run: |
        go test -v -ldflags "$LDFLAGS"

    - name: Build
      run: |
        ARCH=('amd64' 'arm64')
        OS=('linux' 'windows')

        for GOARCH in "${ARCH[@]}"; do
          [[ "$GOARCH" == "arm64" ]] && export CC="aarch64-unknown-linux-musl-cc"

          for GOOS in "${OS[@]}"; do
            export GOARCH
            export GOOS

            ARTIFACT_NAME="${BINARY_NAME}-${GOOS}-${GOARCH}"

            if [[ "$GOOS" == "windows" ]]; then
              ARTIFACT_NAME="${ARTIFACT_NAME}.exe"
              export CC="x86_64-w64-mingw32-cc"

              # Skip ARM build for Windows
              [[ "$GOARCH" == "arm64" ]] && continue
            fi

            # Build
            echo "- building artifact: $ARTIFACT_NAME"
            go build -ldflags "$LDFLAGS" -o $ARTIFACT_NAME

            # Release
            if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              echo "- uploading artifact: $ARTIFACT_NAME"
              gh release upload $GITHUB_REF_NAME $ARTIFACT_NAME --clobber
            fi
          done
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
